In [19]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [20]:
data = np.random.randint(0,100,(10,2))
data

array([[49, 76],
       [34, 86],
       [47, 69],
       [80, 62],
       [ 5, 96],
       [27, 77],
       [26, 10],
       [80, 64],
       [26, 92],
       [20, 37]])

In [21]:
scaler_model = MinMaxScaler()
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [22]:
scaler_model.fit(data)

c:\miniconda3\envs\tensorflow-env\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [23]:
scaler_model.transform(data)

array([[0.58666667, 0.76744186],
       [0.38666667, 0.88372093],
       [0.56      , 0.68604651],
       [1.        , 0.60465116],
       [0.        , 1.        ],
       [0.29333333, 0.77906977],
       [0.28      , 0.        ],
       [1.        , 0.62790698],
       [0.28      , 0.95348837],
       [0.2       , 0.31395349]])

In [30]:
import pandas as pd

In [31]:
data2 = np.random.randint(0,101,(50,4))

In [32]:
df =pd.DataFrame(data=data2,columns=['f1','f2','f3','label'])
df

     f1  f2  f3  label
0    59   6  14     67
1    18  86  81     56
2    69  26  17     63
3    89  43  23     42
4    30  12  92     70
5    47   3  43     21
6    40  73  60     35
7    82  40  31     25
8    99  56  52     40
9    91  63  71     49
10   74  86  99     77
11   74  24  66     37
12   40  78   7     24
13   63  55  87     56
14   92   9  79     36
15   14  80  86     84
16   86  85   7     26
17   31  37  61     38
18   10  14  80     99
19   11  67  60     34
20   63  78  30      7
21   62  38  29     91
22   97  37  40     90
23   71  16  91     82
24   40  38  70     39
25   59  64  39     49
26   71  89  65     12
27   17  50   7     81
28   43  33  14     99
29   51  61  69     98
30   13  18  45      6
31    1   5  21     97
32    4   9  97     28
33   81  33  52     95
34   39  98  11     74
35   67  88  16     64
36  100  91   3     60
37   79  46  74     98
38    3  34  83     20
39   79  52  32     29
40   28  76   2     55
41   92   3  15     85
42   41  63  53     38
43   99  64  32     43
44   11  19  61     63
45   83  70  77     95
46   93  27  76      0
47   39  47  51     54
48    1  11  50     50
49   48  77  97     15

In [34]:
X = df[['f1','f2','f3']]
X

     f1  f2  f3
0    59   6  14
1    18  86  81
2    69  26  17
3    89  43  23
4    30  12  92
5    47   3  43
6    40  73  60
7    82  40  31
8    99  56  52
9    91  63  71
10   74  86  99
11   74  24  66
12   40  78   7
13   63  55  87
14   92   9  79
15   14  80  86
16   86  85   7
17   31  37  61
18   10  14  80
19   11  67  60
20   63  78  30
21   62  38  29
22   97  37  40
23   71  16  91
24   40  38  70
25   59  64  39
26   71  89  65
27   17  50   7
28   43  33  14
29   51  61  69
30   13  18  45
31    1   5  21
32    4   9  97
33   81  33  52
34   39  98  11
35   67  88  16
36  100  91   3
37   79  46  74
38    3  34  83
39   79  52  32
40   28  76   2
41   92   3  15
42   41  63  53
43   99  64  32
44   11  19  61
45   83  70  77
46   93  27  76
47   39  47  51
48    1  11  50
49   48  77  97

In [36]:
Y = df['label']
Y

0     67
1     56
2     63
3     42
4     70
5     21
6     35
7     25
8     40
9     49
10    77
11    37
12    24
13    56
14    36
15    84
16    26
17    38
18    99
19    34
20     7
21    91
22    90
23    82
24    39
25    49
26    12
27    81
28    99
29    98
30     6
31    97
32    28
33    95
34    74
35    64
36    60
37    98
38    20
39    29
40    55
41    85
42    38
43    43
44    63
45    95
46     0
47    54
48    50
49    15
Name: label, dtype: int32

In [37]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=12)

In [42]:
X_train.shape

(33, 3)

In [43]:
X_test.shape

(17, 3)