In [3]:
import pandas as pd

In [4]:
pwd

'F:\\DeepLearningProjects\\Tensorflow-play'

In [7]:
df = pd.read_csv('SuperStore Sales.csv')

In [8]:
df

,Id,Type,Quantity,Sales,Shipping,Customer Name,Province,Region
0,1,Office Supplies,6,261.5400,Regular Air,Muhammed MacIntyre,Nunavut,Nunavut
1,2,Office Supplies,49,10123.0200,Delivery Truck,Barry French,Nunavut,Nunavut
2,3,Office Supplies,27,244.5700,Regular Air,Barry French,Nunavut,Nunavut
3,4,Technology,30,4965.7595,Regular Air,Clay Rozendal,Nunavut,Nunavut
4,5,Office Supplies,19,394.2700,Regular Air,Carlos Soltero,Nunavut,Nunavut
5,6,Furniture,21,146.6900,Regular Air,Carlos Soltero,Nunavut,Nunavut
6,7,Office Supplies,12,93.5400,Regular Air,Carl Jackson,Nunavut,Nunavut
7,8,Office Supplies,22,905.0800,Regular Air,Carl Jackson,Nunavut,Nunavut
8,9,Office Supplies,21,2781.8200,Express Air,Monica Federle,Nunavut,Nunavut
9,10,Office Supplies,44,228.4100,Regular Air,Dorothy Badders,Nunavut,Nunavut
10,11,Office Supplies,45,196.8500,Regular Air,Neola Schneider,Nunavut,Nunavut
11,12,Office Supplies,32,124.5600,Regular Air,Neola Schneider,Nunavut,Nunavut
12,13,Office Supplies,32,716.8400,Regular Air,Carlos Daly,Nunavut,Nunavut
13,14,Technology,31,1474.3300,Regular Air,Carlos Daly,Nunavut,Nunavut
14,15,Office Supplies,15,80.6100,Regular Air,Claudia Miner,Nunavut,Nunavut
15,16,Furniture,46,1815.4900,Regular Air,Neola Schneider,Nunavut,Nunavut
16,17,Office Supplies,16,248.2600,Regular Air,Allen Rosenblatt,Nunavut,Nunavut
17,18,Furniture,44,4462.2300,Delivery Truck,Sylvia Foulston,Nunavut,Nunavut
18,19,Furniture,11,663.7840,Regular Air,Sylvia Foulston,Nunavut,Nunavut
19,20,Technology,15,834.9040,Regular Air,Jim Radford,Nunavut,Nunavut
20,21,Technology,18,2480.9205,Regular Air,Jim Radford,Nunavut,Nunavut
21,22,Office Supplies,13,59.0300,Express Air,Carlos Soltero,Nunavut,Nunavut
22,23,Office Supplies,21,97.4800,Regular Air,Carlos Soltero,Nunavut,Nunavut
23,24,Office Supplies,33,511.8300,Regular Air,Carl Ludwig,Nunavut,Nunavut
24,25,Technology,38,184.9900,Regular Air,Carl Ludwig,Nunavut,Nunavut
25,26,Office Supplies,30,80.9000,Regular Air,Don Miller,Nunavut,Nunavut
26,27,Office Supplies,23,67.2400,Regular Air,Annie Cyprus,Nunavut,Nunavut
27,28,Technology,25,12028.2300,Delivery Truck,Carl Ludwig,Nunavut,Nunavut
28,29,Office Supplies,28,370.4800,Regular Air,Carlos Soltero,Nunavut,Nunavut
29,30,Office Supplies,49,278.0000,Regular Air,Grant Carroll,Nunavut,Nunavut
...,...,...,...,...,...,...,...,...
8369,8370,Office Supplies,6,22.8900,Regular Air,Christopher Conant,Alberta,West
8370,8371,Office Supplies,18,271.8500,Regular Air,Christopher Conant,Alberta,West
8371,8372,Furniture,46,12719.7000,Delivery Truck,Ruben Dartt,Alberta,West
8372,8373,Office Supplies,48,109.7800,Regular Air,Ruben Dartt,Alberta,West
8373,8374,Office Supplies,26,561.6600,Regular Air,Andy Yotov,Alberta,West
8374,8375,Furniture,19,1851.6200,Delivery Truck,Andy Yotov,Alberta,West
8375,8376,Furniture,24,2453.3000,Delivery Truck,Andrew Roberts,Alberta,West
8376,8377,Office Supplies,29,147.0200,Regular Air,Andrew Roberts,Alberta,West
8377,8378,Technology,50,1558.9425,Regular Air,Tony Sayre,Alberta,West
8378,8379,Office Supplies,48,257.3900,Regular Air,Nicole Brennan,Alberta,West
8379,8380,Office Supplies,36,163.5400,Express Air,Jessica Myrick,Alberta,West
8380,8381,Technology,31,2390.5400,Regular Air,Jessica Myrick,Alberta,West
8381,8382,Furniture,48,4644.8700,Delivery Truck,Jessica Myrick,Alberta,West
8382,8383,Office Supplies,9,38.9600,Regular Air,Nicole Brennan,Alberta,West
8383,8384,Furniture,38,978.4000,Delivery Truck,Jason Fortune,Alberta,West
8384,8385,Technology,47,5126.4180,Regular Air,Jason Fortune,Alberta,West
8385,8386,Office Supplies,23,82.1200,Regular Air,Harry Greene,Alberta,West
8386,8387,Office Supplies,8,22.8500,Regular Air,Frank Hawley,Alberta,West
8387,8388,Technology,16,12007.0500,Delivery Truck,Frank Hawley,Alberta,West
8388,8389,Technology,31,5347.9875,Regular Air,Jason Fortune,Alberta,West
8389,8390,Office Supplies,43,322.4700,Express Air,Grant Donatelli,Alberta,West
8390,8391,Furniture,49,1488.6600,Regular Air,Mick Brown,Alberta,West
8391,8392,Furniture,25,2200.6400,Delivery Truck,Frank Hawley,Alberta,West
8392,8393,Office Supplies,34,1041.6600,Express Air,Harry Greene,Alberta,West
8393,8394,Technology,41,10071.0900,Delivery Truck,Harry Greene,Alberta,West
8394,8395,Furniture,8,1294.0400,Delivery Truck,Mick Brown,Alberta,West
8395,8396,Office Supplies,23,392.5700,Regular Air,Mick Brown,Alberta,West
8396,8397,Furniture,37,823.7800,Express Air,Frank Hawley,Alberta,West
8397,8398,Technology,8,469.8375,Regular Air,Frank Hawley,Alberta,West
8398,8399,Furniture,20,2026.0100,Express Air,Grant Donatelli,Alberta,West

In [11]:
df[d

        Id       Customer Name
0        1  Muhammed MacIntyre
1        2        Barry French
2        3        Barry French
3        4       Clay Rozendal
4        5      Carlos Soltero
5        6      Carlos Soltero
6        7        Carl Jackson
7        8        Carl Jackson
8        9      Monica Federle
9       10     Dorothy Badders
10      11     Neola Schneider
11      12     Neola Schneider
12      13         Carlos Daly
13      14         Carlos Daly
14      15       Claudia Miner
15      16     Neola Schneider
16      17    Allen Rosenblatt
17      18     Sylvia Foulston
18      19     Sylvia Foulston
19      20         Jim Radford
20      21         Jim Radford
21      22      Carlos Soltero
22      23      Carlos Soltero
23      24         Carl Ludwig
24      25         Carl Ludwig
25      26          Don Miller
26      27        Annie Cyprus
27      28         Carl Ludwig
28      29      Carlos Soltero
29      30       Grant Carroll
...    ...                 ...
8369  8370  Christopher Conant
8370  8371  Christopher Conant
8371  8372         Ruben Dartt
8372  8373         Ruben Dartt
8373  8374          Andy Yotov
8374  8375          Andy Yotov
8375  8376      Andrew Roberts
8376  8377      Andrew Roberts
8377  8378          Tony Sayre
8378  8379      Nicole Brennan
8379  8380      Jessica Myrick
8380  8381      Jessica Myrick
8381  8382      Jessica Myrick
8382  8383      Nicole Brennan
8383  8384       Jason Fortune
8384  8385       Jason Fortune
8385  8386        Harry Greene
8386  8387        Frank Hawley
8387  8388        Frank Hawley
8388  8389       Jason Fortune
8389  8390     Grant Donatelli
8390  8391          Mick Brown
8391  8392        Frank Hawley
8392  8393        Harry Greene
8393  8394        Harry Greene
8394  8395          Mick Brown
8395  8396          Mick Brown
8396  8397        Frank Hawley
8397  8398        Frank Hawley
8398  8399     Grant Donatelli

[8399 rows x 2 columns]

In [12]:
df['Sales'].max()

89061.05

In [13]:
df.describe()

                Id     Quantity         Sales
count  8399.000000  8399.000000   8399.000000
mean   4200.000000    25.571735   1775.878179
std    2424.726789    14.481071   3585.050525
min       1.000000     1.000000      2.240000
25%    2100.500000    13.000000    143.195000
50%    4200.000000    26.000000    449.420000
75%    6299.500000    38.000000   1709.320000
max    8399.000000    50.000000  89061.050000

In [14]:
df['Sales'] > 50000

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
8369    False
8370    False
8371    False
8372    False
8373    False
8374    False
8375    False
8376    False
8377    False
8378    False
8379    False
8380    False
8381    False
8382    False
8383    False
8384    False
8385    False
8386    False
8387    False
8388    False
8389    False
8390    False
8391    False
8392    False
8393    False
8394    False
8395    False
8396    False
8397    False
8398    False
Name: Sales, Length: 8399, dtype: bool

In [ ]:
df[df['Sales']> 50000]